export const companyData = {
  name: "Satluj Stones Crushing Mills",
  shortName: "Satluj Stones",
  badge: "Industrial Recovery • Material Processing • Circular Manufacturing",
  tagline: "Transforming slag into value-driven industrial materials.",
  headline:
    "From steel waste to engineered output, we turn slag into granulated sand and recovered metal.",
  summary:
    "Satluj Stones Crushing Mills sources slag from Jindal Stainless Steel, Hisar, processes it with specialized crushing and separation systems, produces Granulated Slag Sand, and recovers metal for further purification.",
  description:
    "Built around industrial discipline and resource efficiency, our process reduces waste, extracts reusable metal, and delivers a sand-like finished product suitable for downstream use.",
  contact: {
    phone: "+91-9812531501",
    address: "Hisar, Haryana, India",
    email: "satluj65@gmail.com",
    mapUrl: "https://maps.app.goo.gl/tgSmPed6iVaFb5eY6",
  },
  founder: {
    name: "Rajiv Kumar Garg",
    role: "Founder",
    bio: "Rajiv Kumar Garg leads Satluj Stones Crushing Mills with a practical focus on industrial processing, material recovery, and long-term business relationships.",
    image: "/media/rajiv-kumar-garg.jpeg",
  },
  ctas: {
    primary: "Talk to Our Team",
    secondary: "Explore the Process",
  },
  stats: [
    { label: "Input Material", value: "Steel slag" },
    { label: "Flagship Output", value: "Granulated Slag Sand" },
    { label: "Recovery Method", value: "Magnetic separation" },
    { label: "Operating Focus", value: "Waste-to-value" },
  ],
  process: [
    {
      step: "01",
      title: "Raw Slag Intake",
      copy:
        "We receive slag generated by stainless steel manufacturing and prepare it for controlled processing.",
    },
    {
      step: "02",
      title: "Crushing and Screening",
      copy:
        "The raw material is processed through crushing systems to achieve the desired size profile and consistency.",
    },
    {
      step: "03",
      title: "Metal Recovery",
      copy:
        "Magnetic separation is used to extract metal fractions that can then be purified for industrial reuse.",
    },
    {
      step: "04",
      title: "Finished Product Delivery",
      copy:
        "The processed sand-like material is finished as Granulated Slag Sand for commercial use and dispatch.",
    },
  ],
  products: [
    {
      title: "Granulated Slag Sand",
      description:
        "A fine, sand-like processed material created from slag through a controlled crushing and grading workflow.",
      image: "/media/granulated-slag-sand.jpeg",
    },
    {
      title: "Recovered Metal",
      description:
        "Ferrous metal extracted through magnetic recovery and further refined for reuse in the industrial cycle.",
      image: "/media/recovered-metal.jpeg",
    },
  ],
  gallery: [
    {
      title: "Granulated Slag Sand",
      type: "image" as const,
      src: "/media/granulated-slag-sand.jpeg",
    },
    {
      title: "Recovered Metal",
      type: "image" as const,
      src: "/media/recovered-metal.jpeg",
    },
    {
      title: "Plant Operation Video",
      type: "video" as const,
      src: "/media/plant-overview.mp4",
      poster: "/media/granulated-slag-sand.jpeg",
    },
  ],
  adminSections: [
    {
      title: "Company Profile",
      detail: "Edit the company story, founder profile, contact data, and visitor-facing homepage copy.",
    },
    {
      title: "Gallery and Media",
      detail: "Manage product images, process photos, and plant videos used across the website.",
    },
    {
      title: "Leads and Inquiries",
      detail: "Track incoming business inquiries, callback requests, and partnership conversations.",
    },
    {
      title: "Operations Overview",
      detail: "Monitor material intake, processed output, recovered metal, and internal production notes.",
    },
  ],
};

export type GalleryItem = (typeof companyData.gallery)[number];
